var emojis = [
    {code:':b',class:'lengua'},
    {code:'xD',class:'XD'},
    {code:':\\)',class:'smile'},
    {code:'think',class:'think'},
    {code:':D',class:'smile1'},
    {code:';\\)',class:'wink'},
    {code:'angel',class:'angel'},
    {code:'zzz',class:'zzz'},
    {code:'shame',class:'shame'},
    {code:'laugh',class:'laugh'},
    {code:'kiss',class:'kiss'},
    {code: 'cuteSmile',class:'cuteSmile'},
    {code: 'heartEyes',class:'heartEyes'},
    {code: ':O',class:'surprise'},
];